from __future__ import annotations

LANGUAGES = {
    "en": {
        "app_title": "HomRec v1.7.1", "live_preview": "PREVIEW", "ready": "Ready",
        "recording": "Recording", "paused": "Paused", "fps": "FPS:", "resolution": "Resolution:",
        "start": "▶ START", "pause": "⏸ PAUSE", "stop": "■ STOP", "resume": "▶ RESUME",
        "recording_btn": "⏺ RECORDING", "audio_mixer": "Audio Mixer", "microphone": "Microphone",
        "desktop_audio": "Desktop Audio", "mute": "Mute", "unmute": "Unmute", "vol": "Vol:",
        "level": "Level:", "enable_audio": "Enable Audio", "ffmpeg_found": "FFmpeg: ✅ Found",
        "ffmpeg_not_found": "FFmpeg: ❌ Not Found", "file_menu": "File",
        "open_recordings": "Open Recordings Folder", "exit": "Exit", "view_menu": "View",
        "always_on_top": "Always on Top", "fullscreen": "Fullscreen  F11",
        "pc_analytics": "PC Analytics", "cpu_info": "CPU Info", "ram_info": "RAM Info",
        "disk_info": "Disk Info", "help_menu": "Help", "check_updates": "Check for Updates",
        "report_issue": "Report Issue", "capture_source": "Capture Source",
        "full_desktop": "Full Desktop", "select_window": "Select Window...",
        "minimize_tray": "Minimize to tray on close", "language": "Language",
        "english": "English", "russian": "Русский", "theme": "Theme", "dark": "Dark",
        "light": "Light", "settings_menu": "Settings", "preferences": "Preferences...",
        "performance_menu": "Performance", "ultra": "Ultra (60 FPS)", "turbo": "Turbo (30 FPS)",
        "balanced": "Balanced (15 FPS)", "eco": "Eco (8 FPS)", "stats": "STATS",
        "time": "TIME", "status": "STATUS", "warning": "Warning", "error": "Error",
        "info": "Info", "folder_not_exist": "Folder doesn't exist!",
        "recording_failed": "Recording failed!", "settings_saved": "Settings saved!",
        "recording_saved": "✅ Recording Saved!", "open_folder": "Open folder?",
        "ffmpeg_not_found_msg": "⚠️ FFmpeg not found - audio separate",
        "saved": "✅ Saved: {size:.1f} MB | {duration:.1f}s",
        "recording_status": "Recording: {size:.1f} MB | {frames} frames",
        "file": "📁 File:", "size": "📊 Size:", "duration": "⏱️ Duration:",
        "audio": "🎤 Audio:", "merged": "Merged", "separate": "Separate", "no_audio": "No",
        "save": "Save", "cancel": "Cancel", "browse": "Browse",
        "output_folder": "Output folder:", "settings_title": "Settings",
        "video_settings": "Video", "quality": "Quality:", "mode": "Mode:",
        "advanced": "Advanced", "monitor": "Monitor:", "output": "Output:",
        "countdown": "Countdown (3s)", "timestamp": "Timestamp", "cursor": "Cursor",
        "notification": "Show summary", "made_by": "Homa4ella", "audio_file": "🎵 Audio file:",
        "show_log": "Show Log",
    }
}
