"""core/languages.py — built-in languages"""

LANGUAGES = {
    "en": {
        "app_title": "HomRec (v2.0.0)",
        "live_preview": "PREVIEW",
        "ready": "Ready",
        "recording": "Recording",
        "paused": "Paused",
        "fps": "FPS:",
        "resolution": "Resolution:",
        "start": "▶ START",
        "pause": "⏸ PAUSE",
        "stop": "■ STOP",
        "resume": "▶ RESUME",
        "recording_btn": "⏺ RECORDING",
        "audio_mixer": "Audio Mixer",
        "microphone": "Microphone",
        "desktop_audio": "Desktop Audio",
        "mute": "Mute",
        "unmute": "Unmute",
        "vol": "Vol:",
        "level": "Level:",
        "enable_audio": "Enable Audio",
        "ffmpeg_found": "FFmpeg: ✅ Found",
        "ffmpeg_not_found": "FFmpeg: ❌ Not Found",
        "file_menu": "File",
        "open_recordings": "Open Recordings Folder",
        "exit": "Exit",
        "view_menu": "View",
        "always_on_top": "Always on Top",
        "fullscreen": "Fullscreen  F11",
        "pc_analytics": "PC Analytics",
        "cpu_info": "CPU Info",
        "ram_info": "RAM Info",
        "disk_info": "Disk Info",
        "help_menu": "Help",
        "check_updates": "Check for Updates",
        "report_issue": "Report Issue",
        "capture_source": "Capture Source",
        "full_desktop": "Full Desktop",
        "select_window": "Select Window...",
        "minimize_tray": "Minimize to tray on close",
        "language": "Language",
        "english": "English",
        "russian": "Русский",
        "theme": "Theme",
        "dark": "Dark",
        "light": "Light",
        "settings_menu": "Settings",
        "preferences": "Preferences...",
        "performance_menu": "Performance",
        "ultra": "Ultra (60 FPS)",
        "turbo": "Turbo (30 FPS)",
        "balanced": "Balanced (15 FPS)",
        "eco": "Eco (8 FPS)",
        "stats": "STATS",
        "time": "TIME",
        "status": "STATUS",
        "warning": "Warning",
        "error": "Error",
        "info": "Info",
        "folder_not_exist": "Folder doesn't exist!",
        "recording_failed": "Recording failed!",
        "settings_saved": "Settings saved!",
        "recording_saved": "✅ Recording Saved!",
        "open_folder": "Open folder?",
        "ffmpeg_not_found_msg": "⚠️ FFmpeg not found - audio separate",
        "saved": "✅ Saved: {size:.1f} MB | {duration:.1f}s",
        "recording_status": "Recording: {size:.1f} MB | {frames} frames",
        "file": "📁 File:",
        "size": "📊 Size:",
        "duration": "⏱️ Duration:",
        "audio": "🎤 Audio:",
        "merged": "Merged",
        "separate": "Separate",
        "no_audio": "No",
        "save": "Save",
        "cancel": "Cancel",
        "browse": "Browse",
        "output_folder": "Output folder:",
        "settings_title": "Settings",
        "video_settings": "Video",
        "quality": "Quality:",
        "mode": "Mode:",
        "advanced": "Advanced",
        "monitor": "Monitor:",
        "output": "Output:",
        "countdown": "Countdown (3s)",
        "timestamp": "Timestamp",
        "cursor": "Cursor",
        "notification": "Show summary",
        "made_by": "Homa4ella",
        "audio_file": "🎵 Audio file:",
    },
    "ru": {
        "app_title": "HomRec (v2.0.0)",
        "live_preview": "ПРЕДПРОСМОТР",
        "ready": "Готов",
        "recording": "Запись",
        "paused": "Пауза",
        "fps": "FPS:",
        "resolution": "Разрешение:",
        "start": "▶ СТАРТ",
        "pause": "⏸ ПАУЗА",
        "stop": "■ СТОП",
        "resume": "▶ ПРОДОЛЖИТЬ",
        "recording_btn": "⏺ ЗАПИСЬ",
        "audio_mixer": "Аудио Микшер",
        "microphone": "Микрофон",
        "desktop_audio": "Системный звук",
        "mute": "Выкл",
        "unmute": "Вкл",
        "vol": "Громк:",
        "level": "Уровень:",
        "enable_audio": "Запись звука",
        "ffmpeg_found": "FFmpeg: ✅ Найден",
        "ffmpeg_not_found": "FFmpeg: ❌ Не найден",
        "file_menu": "Файл",
        "open_recordings": "Открыть папку",
        "exit": "Выход",
        "view_menu": "Вид",
        "always_on_top": "Поверх окон",
        "fullscreen": "Полный экран F11",
        "pc_analytics": "Аналитика",
        "cpu_info": "Инфо CPU",
        "ram_info": "Инфо RAM",
        "disk_info": "Инфо диска",
        "language": "Язык",
        "english": "English",
        "russian": "Русский",
        "theme": "Тема",
        "dark": "Темная",
        "light": "Светлая",
        "settings_menu": "Настройки",
        "preferences": "Параметры...",
        "performance_menu": "Производительность",
        "ultra": "Ультра (60 FPS)",
        "turbo": "Турбо (30 FPS)",
        "balanced": "Средний (15 FPS)",
        "eco": "Эко (8 FPS)",
        "stats": "СТАТИСТИКА",
        "time": "ВРЕМЯ",
        "status": "СТАТУС",
        "warning": "Предупреждение",
        "error": "Ошибка",
        "info": "Информация",
        "folder_not_exist": "Папка не существует!",
        "recording_failed": "Ошибка записи!",
        "settings_saved": "Настройки сохранены!",
        "recording_saved": "✅ Запись сохранена!",
        "open_folder": "Открыть папку?",
        "ffmpeg_not_found_msg": "⚠️ FFmpeg не найден - аудио отдельно",
        "saved": "✅ Сохранено: {size:.1f} МБ | {duration:.1f}с",
        "recording_status": "Запись: {size:.1f} МБ | {frames} кадров",
        "file": "📁 Файл:",
        "size": "📊 Размер:",
        "duration": "⏱️ Длительность:",
        "audio": "🎤 Аудио:",
        "merged": "Объединено",
        "separate": "Отдельно",
        "no_audio": "Нет",
        "save": "Сохранить",
        "cancel": "Отмена",
        "browse": "Обзор",
        "output_folder": "Папка записей:",
        "settings_title": "Настройки",
        "video_settings": "Видео",
        "quality": "Качество:",
        "mode": "Режим:",
        "advanced": "Дополнительно",
        "monitor": "Монитор:",
        "output": "Папка:",
        "countdown": "Отсчет (3с)",
        "timestamp": "Время",
        "cursor": "Курсор",
        "notification": "Показывать сводку",
        "made_by": "Homa4ella",
        "audio_file": "🎵 Аудио файл:",
        "help_menu": "Справка",
        "check_updates": "Проверить обновления",
        "report_issue": "Сообщить об ошибке",
        "capture_source": "Источник",
        "full_desktop": "Весь экран",
        "select_window": "Выбрать окно...",
        "minimize_tray": "Сворачивать в трей",
    }
}

# ==================== HELPER FUNCTIONS ====================

